name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release Binaries 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.5'
    
    - name: Build Binary
      run: |
        # Set target OS and Architecture, then build
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o gh-activity-${{ matrix.goos }}-${{ matrix.goarch }}
        
        # Windows requires the .exe file extension
        if [ "${{ matrix.goos}}" = "windows" ]; then
          mv gh-activity-${{ matrix.goos }}-${{ matrix.goarch }} gh-activity-${{ matrix.goos }}-${{ matrix.goarch }}.exe
        fi
      
    - name: Upload to Github Release
      uses: softprops/action-gh-release@v2
      with:
        files: gh-activity-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}